language: ruby
rvm:
  - 2.7.1
env:
  - DB=postgresql SECRET=WHOAREYOU BASE_URL=baseurl
services:
  - postgresql
  - redis-server
install: bundle install
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec --format doc
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database mydb_test;' -U postgres